0
:
alt_artist_ids
:
[]
alt_classification_ids
:
(2)['TM-5', 'TM-4']
alt_image_ids
:
[]
alt_material_ids
:
['TM-2410']
alt_style_ids
:
[]
alt_subject_ids
:
[]
alt_technique_ids
:
[]
alt_titles
:
null
api_link
:
"https://api.artic.edu/api/v1/artworks/7122"
api_model
:
"artworks"
artist_display
:
"Max Beckmann\nGerman, 1884-1950"
artist_id
:
33571
artist_ids
:
[33571]
artist_title
:
"Max Beckmann"
artist_titles
:
['Max Beckmann']
artwork_type_id
:
14
artwork_type_title
:
"Drawing and Watercolor"
boost_rank
:
null
catalogue_display
:
null
category_ids
:
['PC-13']
category_titles
:
['Prints and Drawings']
classification_id
:
"TM-175"
classification_ids
:
(3)['TM-175', 'TM-5', 'TM-4']
classification_title
:
"graphite"
classification_titles
:
(3)['graphite', 'drawings (visual works)', 'prints and drawing']
color
:
{ h: 40, l: 54, s: 41, percentage: 0.0007339456274730527, population: 8 }
colorfulness
:
16.8627
copyright_notice
:
"© 2018 Artists Rights Society (ARS), New York / VG Bild-Kunst, Bonn"
credit_line
:
"Gift of the Print and Drawing Club"
date_display
:
"1918"
date_end
:
1918
date_qualifier_id
:
null
date_qualifier_title
:
""
date_start
:
1918
department_id
:
"PC-13"
department_title
:
"Prints and Drawings"
description
:
null
dimensions
:
"50.4 × 32.9 cm (19 7/8 × 13 in.)"
dimensions_detail
:
[{… }]
document_ids
:
[]
edition
:
null
exhibition_history
:
"Mannheim, Germany, Städtische Kunsthalle Mannheim, \"Max Beckmann – das gesammelte Werk,\" 1928, cat. 126 (?).\n\nFrankfurt, Germany, Kunstkabinett Hanna Bekker vom Rath, \"Max Beckmann,\" July 9-August 12, 1955, cat. 16. \n\nPfälzisch Landesgeurbeanstalt, Kaiserslautern, \"Max Beckmann,\" September 29-October 29, 1956, cat. 16.\n\nFrankfurt, Germany, Kunstkabinett Hanna Bekker vom Rath, \"Gemälde, Aquarelle, Handzeichnungen, Graphik, Plastik des 20 Jahrs,\" 1956-1957, cat. 20. \n\nMunich, Haus der Kunst, \"Max Beckmann,\" February 25-April 23, 1984, cat. 154, cat. by Carla Schulz-Hoffmann and Judith C. Weiss, et. al.; traveled to Berlin, Nationalgalerie, May 18-July 29, 1984; the St. Louis Art Museum, September 7-November 4, 1984; the Los Angeles County Museum of Art, December 9, 1984-February 3, 1985.\n\nNew York, Neue Galerie, \"Max Beckmann: Formative Years, 1915-1925\", October 5, 2023 - January 15, 2024."
fiscal_year
:
null
fiscal_year_deaccession
:
null
gallery_id
:
null
gallery_title
:
null
has_advanced_imaging
:
false
has_educational_resources
:
false
has_multimedia_resources
:
false
has_not_been_viewed_much
:
false
id
:
7122
image_id
:
"f2a2c17c-8eee-a1b8-cfe4-71bb59f3798e"
inscriptions
:
null
internal_department_id
:
3
is_boosted
:
false
is_on_view
:
false
is_public_domain
:
false
is_zoomable
:
true
latitude
:
null
latlon
:
null
longitude
:
null
main_reference_number
:
"1958.15"
material_id
:
"TM-2982"
material_ids
:
(2)['TM-2982', 'TM-2410']
material_titles
:
(2)['paper (fiber product)', 'graphite']
max_zoom_window_size
:
1280
medium_display
:
"Graphite on cream laid paper"
nomisma_id
:
null
on_loan_display
:
"<p>On loan to Neue Galerie New York in New York City for <i>Max Beckmann: Formative Years, 1915-1925</i></p>"
place_of_origin
:
"Germany"
provenance_text
:
"Sold by Zinglers Kabinett, Frankfurt, to the Kunsthalle Mannheim [Lugt 1781E], 1924 [former inventory number G1952; according to records of the Kunsthalle Mannheim]; sequestrated Aug. 28, 1937 by the Reichsministerium für Volksaufklärung und Propaganda, Berlin (EK 6173); sold by Hildebrand Gurlitt, 1941 [records of the Kunsthalle Mannheim and an email from Hedda Finke of May 28, 2020].  Frankfurter Kunstkabinett Hanna Bekker vom Rath (opened 1947), by 1955 [Frankfurt 1955].  Sold by Allan Frumkin, New York, to the Art Institute, 1958."
publication_history
:
"Stephan von Weise, Max Beckmanns Zeichnerisches work 1903-1925 (Dussledorf, 1978), pp. 133 and 214, no. 403 (ill.).\n\nKaroline Hille, Spuren der Moderne: Die Mannheimer Kunsthalle von 1918 bis 1933 (Berlin, 1994), pp. 321 and 380."
publishing_verification_level
:
"Web Cataloged"
section_ids
:
[]
section_titles
:
[]
site_ids
:
[]
sound_ids
:
[]
source_updated_at
:
"2023-10-28T00:30:01-05:00"
style_id
:
null
style_ids
:
[]
style_title
:
null
style_titles
:
[]
subject_id
:
null
subject_ids
:
[]
subject_titles
:
[]
suggest_autocomplete_all
:
(2)[{… }, {… }]
technique_id
:
null
technique_ids
:
[]
technique_titles
:
[]
term_titles
:
(5)['graphite', 'paper (fiber product)', 'graphite', 'drawings (visual works)', 'prints and drawing']
text_ids
:
[]
theme_titles
:
[]
thumbnail
:
{ lqip: 'data:image/gif;base64,R0lGODlhAwAFAPMAANXCo9bDpdfD…AACH5BAAAAAAALAAAAAADAAUAAAQLsDmWDiIDFBGWMhEAOw==', width: 1467, height: 2250, alt_text: 'A work made of graphite on cream laid paper.' }
timestamp
:
"2023-10-28T08:48:20-05:00"
title
:
"Seated Boy"
updated_at
:
"2023-10-28T00:31:38-05:00"
video_ids
:
[]